---
deployment:
 tasks:
 - export DEPLOYPATH=/home/pakrashan/public_html
 - /bin/cp index.php $DEPLOYPATH
 - /bin/cp style.css $DEPLOYPATH
 - /bin/cp add-info.php $DEPLOYPATH
 - /bin/cp add-volunteer.php $DEPLOYPATH
 - /bin/cp logout.php $DEPLOYPATH
 - /bin/cp req.php $DEPLOYPATH
 - /bin/cp https://github.com/AliTechGeek52/pak-rashan.git $DEPLOYPATH
