---
deployment:
 tasks:
 - export DEPLOYPATH=/home/pakrashan/public_html
 - /bin/cp -R images $DEPLOYPATH
 - /bin/cp index.php $DEPLOYPATH
 - /bin/cp style.css $DEPLOYPATH
 - /bin/cp add-info.php $DEPLOYPATH
 - /bin/cp add-volunteer.php $DEPLOYPATH
 - /bin/cp logout.php $DEPLOYPATH
 - /bin/cp req.php $DEPLOYPATH
 - /bin/cp .github/workflows $DEPLOYPATH
 - /bin/cp .vscode $DEPLOYPATH
 - /bin/cp pakrashan_rashan.sql $DEPLOYPATH
